package de.htw_berlin.HoboOthello.Core;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import org.junit.Test;

import static org.junit.Assert.*;

/**
 * Created by fubu on 11.12.16.
 */
public class GameRuleTest {
    @Test
    public void changeAllPossibleFieldsToTrue() throws Exception {
        String content;

        Field[][] fields;
        Gson gson = new GsonBuilder().create();

        // test 1
        content = "[[{\"x\":0,\"y\":0,\"possibleMove\":false},{\"x\":0,\"y\":1,\"possibleMove\":false},{\"x\":0,\"y\":2,\"possibleMove\":false},{\"x\":0,\"y\":3,\"possibleMove\":false},{\"x\":0,\"y\":4,\"possibleMove\":false},{\"x\":0,\"y\":5,\"possibleMove\":false},{\"x\":0,\"y\":6,\"possibleMove\":false},{\"x\":0,\"y\":7,\"possibleMove\":false}],[{\"x\":1,\"y\":0,\"possibleMove\":false},{\"x\":1,\"y\":1,\"possibleMove\":false},{\"x\":1,\"y\":2,\"possibleMove\":false},{\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"x\":1,\"y\":5,\"possibleMove\":false},{\"x\":1,\"y\":6,\"possibleMove\":false},{\"x\":1,\"y\":7,\"possibleMove\":false}],[{\"x\":2,\"y\":0,\"possibleMove\":false},{\"x\":2,\"y\":1,\"possibleMove\":false},{\"x\":2,\"y\":2,\"possibleMove\":false},{\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":5,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":6,\"possibleMove\":false},{\"x\":2,\"y\":7,\"possibleMove\":false}],[{\"x\":3,\"y\":0,\"possibleMove\":false},{\"x\":3,\"y\":1,\"possibleMove\":false},{\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":4,\"possibleMove\":false},{\"x\":3,\"y\":5,\"possibleMove\":false},{\"x\":3,\"y\":6,\"possibleMove\":false},{\"x\":3,\"y\":7,\"possibleMove\":false}],[{\"x\":4,\"y\":0,\"possibleMove\":false},{\"x\":4,\"y\":1,\"possibleMove\":false},{\"x\":4,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":4,\"possibleMove\":false},{\"x\":4,\"y\":5,\"possibleMove\":false},{\"x\":4,\"y\":6,\"possibleMove\":false},{\"x\":4,\"y\":7,\"possibleMove\":false}],[{\"x\":5,\"y\":0,\"possibleMove\":false},{\"x\":5,\"y\":1,\"possibleMove\":false},{\"x\":5,\"y\":2,\"possibleMove\":false},{\"x\":5,\"y\":3,\"possibleMove\":false},{\"x\":5,\"y\":4,\"possibleMove\":false},{\"x\":5,\"y\":5,\"possibleMove\":false},{\"x\":5,\"y\":6,\"possibleMove\":false},{\"x\":5,\"y\":7,\"possibleMove\":false}],[{\"x\":6,\"y\":0,\"possibleMove\":false},{\"x\":6,\"y\":1,\"possibleMove\":false},{\"x\":6,\"y\":2,\"possibleMove\":false},{\"x\":6,\"y\":3,\"possibleMove\":false},{\"x\":6,\"y\":4,\"possibleMove\":false},{\"x\":6,\"y\":5,\"possibleMove\":false},{\"x\":6,\"y\":6,\"possibleMove\":false},{\"x\":6,\"y\":7,\"possibleMove\":false}],[{\"x\":7,\"y\":0,\"possibleMove\":false},{\"x\":7,\"y\":1,\"possibleMove\":false},{\"x\":7,\"y\":2,\"possibleMove\":false},{\"x\":7,\"y\":3,\"possibleMove\":false},{\"x\":7,\"y\":4,\"possibleMove\":false},{\"x\":7,\"y\":5,\"possibleMove\":false},{\"x\":7,\"y\":6,\"possibleMove\":false},{\"x\":7,\"y\":7,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        GameRule move = new GameRule(fields);
        move.changeAllPossibleFieldsToTrue(Color.BLACK);
        assertEquals(8, move.getPossibleMoves());

        // test 2
        content = "[[{\"x\":0,\"y\":0,\"possibleMove\":false},{\"x\":0,\"y\":1,\"possibleMove\":false},{\"x\":0,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":3,\"possibleMove\":false},{\"x\":0,\"y\":4,\"possibleMove\":false},{\"x\":0,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"x\":1,\"y\":5,\"possibleMove\":false}],[{\"x\":2,\"y\":0,\"possibleMove\":false},{\"x\":2,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"x\":2,\"y\":5,\"possibleMove\":false}],[{\"x\":3,\"y\":0,\"possibleMove\":false},{\"x\":3,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"x\":3,\"y\":4,\"possibleMove\":false},{\"x\":3,\"y\":5,\"possibleMove\":false}],[{\"x\":4,\"y\":0,\"possibleMove\":false},{\"x\":4,\"y\":1,\"possibleMove\":false},{\"x\":4,\"y\":2,\"possibleMove\":false},{\"x\":4,\"y\":3,\"possibleMove\":false},{\"x\":4,\"y\":4,\"possibleMove\":false},{\"x\":4,\"y\":5,\"possibleMove\":false}],[{\"x\":5,\"y\":0,\"possibleMove\":false},{\"x\":5,\"y\":1,\"possibleMove\":false},{\"x\":5,\"y\":2,\"possibleMove\":false},{\"x\":5,\"y\":3,\"possibleMove\":false},{\"x\":5,\"y\":4,\"possibleMove\":false},{\"x\":5,\"y\":5,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        move = new GameRule(fields);
        move.changeAllPossibleFieldsToTrue(Color.WHITE);
        assertEquals(2, move.getPossibleMoves());

        // test 3
        content = "[[{\"x\":0,\"y\":0,\"possibleMove\":false},{\"x\":0,\"y\":1,\"possibleMove\":false},{\"x\":0,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":3,\"possibleMove\":false},{\"x\":0,\"y\":4,\"possibleMove\":false},{\"x\":0,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"x\":1,\"y\":5,\"possibleMove\":false}],[{\"x\":2,\"y\":0,\"possibleMove\":false},{\"x\":2,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"x\":2,\"y\":5,\"possibleMove\":false}],[{\"x\":3,\"y\":0,\"possibleMove\":false},{\"x\":3,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":5,\"possibleMove\":false}],[{\"x\":4,\"y\":0,\"possibleMove\":false},{\"x\":4,\"y\":1,\"possibleMove\":false},{\"x\":4,\"y\":2,\"possibleMove\":false},{\"x\":4,\"y\":3,\"possibleMove\":false},{\"x\":4,\"y\":4,\"possibleMove\":false},{\"x\":4,\"y\":5,\"possibleMove\":false}],[{\"x\":5,\"y\":0,\"possibleMove\":false},{\"x\":5,\"y\":1,\"possibleMove\":false},{\"x\":5,\"y\":2,\"possibleMove\":false},{\"x\":5,\"y\":3,\"possibleMove\":false},{\"x\":5,\"y\":4,\"possibleMove\":false},{\"x\":5,\"y\":5,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        move = new GameRule(fields);
        move.changeAllPossibleFieldsToTrue(Color.WHITE);
        assertEquals(3, move.getPossibleMoves());

        // test 4
        content = "[[{\"x\":0,\"y\":0,\"possibleMove\":false},{\"x\":0,\"y\":1,\"possibleMove\":false},{\"x\":0,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":3,\"possibleMove\":false},{\"x\":0,\"y\":4,\"possibleMove\":false},{\"x\":0,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":5,\"possibleMove\":false}],[{\"x\":2,\"y\":0,\"possibleMove\":false},{\"x\":2,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"x\":2,\"y\":5,\"possibleMove\":false}],[{\"x\":3,\"y\":0,\"possibleMove\":false},{\"x\":3,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":5,\"possibleMove\":false}],[{\"x\":4,\"y\":0,\"possibleMove\":false},{\"x\":4,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":3,\"possibleMove\":false},{\"x\":4,\"y\":4,\"possibleMove\":false},{\"x\":4,\"y\":5,\"possibleMove\":false}],[{\"x\":5,\"y\":0,\"possibleMove\":false},{\"x\":5,\"y\":1,\"possibleMove\":false},{\"x\":5,\"y\":2,\"possibleMove\":false},{\"x\":5,\"y\":3,\"possibleMove\":false},{\"x\":5,\"y\":4,\"possibleMove\":false},{\"x\":5,\"y\":5,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        move = new GameRule(fields);
        move.changeAllPossibleFieldsToTrue(Color.BLACK);
        assertEquals(11, move.getPossibleMoves());

        // test 5
        content = "[[{\"x\":0,\"y\":0,\"possibleMove\":false},{\"x\":0,\"y\":1,\"possibleMove\":false},{\"x\":0,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":3,\"possibleMove\":false},{\"x\":0,\"y\":4,\"possibleMove\":false},{\"x\":0,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":5,\"possibleMove\":false}],[{\"x\":2,\"y\":0,\"possibleMove\":false},{\"x\":2,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"x\":2,\"y\":5,\"possibleMove\":false}],[{\"x\":3,\"y\":0,\"possibleMove\":false},{\"x\":3,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":5,\"possibleMove\":false}],[{\"x\":4,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":3,\"possibleMove\":false},{\"x\":4,\"y\":4,\"possibleMove\":false},{\"x\":4,\"y\":5,\"possibleMove\":false}],[{\"x\":5,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":2,\"possibleMove\":false},{\"x\":5,\"y\":3,\"possibleMove\":false},{\"x\":5,\"y\":4,\"possibleMove\":false},{\"x\":5,\"y\":5,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        move = new GameRule(fields);
        move.changeAllPossibleFieldsToTrue(Color.WHITE);
        assertEquals(5, move.getPossibleMoves());

        // test 6
        content = "[[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":0,\"possibleMove\":false},{\"x\":3,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":5,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        move = new GameRule(fields);
        move.changeAllPossibleFieldsToTrue(Color.WHITE);
        assertEquals(1, move.getPossibleMoves());

        // test 7
        content = "[[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":5,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        move = new GameRule(fields);
        move.changeAllPossibleFieldsToTrue(Color.BLACK);
        assertEquals(0, move.getPossibleMoves());
    }

    @Test
    public void isMoveAllowed() throws Exception {
        String content;

        Field[][] fields;
        Gson gson = new GsonBuilder().create();

        // test 1
        content = "[[{\"x\":0,\"y\":0,\"possibleMove\":false},{\"x\":0,\"y\":1,\"possibleMove\":false},{\"x\":0,\"y\":2,\"possibleMove\":false},{\"x\":0,\"y\":3,\"possibleMove\":true},{\"x\":0,\"y\":4,\"possibleMove\":true},{\"x\":0,\"y\":5,\"possibleMove\":false},{\"x\":0,\"y\":6,\"possibleMove\":false},{\"x\":0,\"y\":7,\"possibleMove\":false}],[{\"x\":1,\"y\":0,\"possibleMove\":false},{\"x\":1,\"y\":1,\"possibleMove\":false},{\"x\":1,\"y\":2,\"possibleMove\":false},{\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"x\":1,\"y\":5,\"possibleMove\":true},{\"x\":1,\"y\":6,\"possibleMove\":false},{\"x\":1,\"y\":7,\"possibleMove\":false}],[{\"x\":2,\"y\":0,\"possibleMove\":false},{\"x\":2,\"y\":1,\"possibleMove\":false},{\"x\":2,\"y\":2,\"possibleMove\":false},{\"x\":2,\"y\":3,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":5,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":6,\"possibleMove\":false},{\"x\":2,\"y\":7,\"possibleMove\":false}],[{\"x\":3,\"y\":0,\"possibleMove\":false},{\"x\":3,\"y\":1,\"possibleMove\":false},{\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":4,\"possibleMove\":false},{\"x\":3,\"y\":5,\"possibleMove\":true},{\"x\":3,\"y\":6,\"possibleMove\":false},{\"x\":3,\"y\":7,\"possibleMove\":false}],[{\"x\":4,\"y\":0,\"possibleMove\":false},{\"x\":4,\"y\":1,\"possibleMove\":false},{\"x\":4,\"y\":2,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":4,\"possibleMove\":false},{\"x\":4,\"y\":5,\"possibleMove\":false},{\"x\":4,\"y\":6,\"possibleMove\":false},{\"x\":4,\"y\":7,\"possibleMove\":false}],[{\"x\":5,\"y\":0,\"possibleMove\":false},{\"x\":5,\"y\":1,\"possibleMove\":false},{\"x\":5,\"y\":2,\"possibleMove\":true},{\"x\":5,\"y\":3,\"possibleMove\":true},{\"x\":5,\"y\":4,\"possibleMove\":false},{\"x\":5,\"y\":5,\"possibleMove\":false},{\"x\":5,\"y\":6,\"possibleMove\":false},{\"x\":5,\"y\":7,\"possibleMove\":false}],[{\"x\":6,\"y\":0,\"possibleMove\":false},{\"x\":6,\"y\":1,\"possibleMove\":false},{\"x\":6,\"y\":2,\"possibleMove\":false},{\"x\":6,\"y\":3,\"possibleMove\":false},{\"x\":6,\"y\":4,\"possibleMove\":false},{\"x\":6,\"y\":5,\"possibleMove\":false},{\"x\":6,\"y\":6,\"possibleMove\":false},{\"x\":6,\"y\":7,\"possibleMove\":false}],[{\"x\":7,\"y\":0,\"possibleMove\":false},{\"x\":7,\"y\":1,\"possibleMove\":false},{\"x\":7,\"y\":2,\"possibleMove\":false},{\"x\":7,\"y\":3,\"possibleMove\":false},{\"x\":7,\"y\":4,\"possibleMove\":false},{\"x\":7,\"y\":5,\"possibleMove\":false},{\"x\":7,\"y\":6,\"possibleMove\":false},{\"x\":7,\"y\":7,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        GameRule move = new GameRule(fields);
        for (Field[] fieldArray : fields) {
            for (Field field : fieldArray) {
                assertEquals(field.isPossibleMove(), move.isMoveAllowed(field, Color.BLACK));
            }
        }

        // test 2
        content = "[[{\"x\":0,\"y\":0,\"possibleMove\":false},{\"x\":0,\"y\":1,\"possibleMove\":false},{\"x\":0,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":3,\"possibleMove\":false},{\"x\":0,\"y\":4,\"possibleMove\":false},{\"x\":0,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"x\":1,\"y\":5,\"possibleMove\":false}],[{\"x\":2,\"y\":0,\"possibleMove\":false},{\"x\":2,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"x\":2,\"y\":5,\"possibleMove\":false}],[{\"x\":3,\"y\":0,\"possibleMove\":false},{\"x\":3,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"x\":3,\"y\":4,\"possibleMove\":true},{\"x\":3,\"y\":5,\"possibleMove\":false}],[{\"x\":4,\"y\":0,\"possibleMove\":false},{\"x\":4,\"y\":1,\"possibleMove\":false},{\"x\":4,\"y\":2,\"possibleMove\":false},{\"x\":4,\"y\":3,\"possibleMove\":false},{\"x\":4,\"y\":4,\"possibleMove\":true},{\"x\":4,\"y\":5,\"possibleMove\":false}],[{\"x\":5,\"y\":0,\"possibleMove\":false},{\"x\":5,\"y\":1,\"possibleMove\":false},{\"x\":5,\"y\":2,\"possibleMove\":false},{\"x\":5,\"y\":3,\"possibleMove\":false},{\"x\":5,\"y\":4,\"possibleMove\":false},{\"x\":5,\"y\":5,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        move = new GameRule(fields);
        for (Field[] fieldArray : fields) {
            for (Field field : fieldArray) {
                assertEquals(field.isPossibleMove(), move.isMoveAllowed(field, Color.WHITE));
            }
        }

        // test 3
        content = "[[{\"x\":0,\"y\":0,\"possibleMove\":false},{\"x\":0,\"y\":1,\"possibleMove\":false},{\"x\":0,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":3,\"possibleMove\":false},{\"x\":0,\"y\":4,\"possibleMove\":false},{\"x\":0,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"x\":1,\"y\":5,\"possibleMove\":true}],[{\"x\":2,\"y\":0,\"possibleMove\":false},{\"x\":2,\"y\":1,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"x\":2,\"y\":5,\"possibleMove\":true}],[{\"x\":3,\"y\":0,\"possibleMove\":false},{\"x\":3,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":5,\"possibleMove\":false}],[{\"x\":4,\"y\":0,\"possibleMove\":false},{\"x\":4,\"y\":1,\"possibleMove\":false},{\"x\":4,\"y\":2,\"possibleMove\":false},{\"x\":4,\"y\":3,\"possibleMove\":false},{\"x\":4,\"y\":4,\"possibleMove\":false},{\"x\":4,\"y\":5,\"possibleMove\":false}],[{\"x\":5,\"y\":0,\"possibleMove\":false},{\"x\":5,\"y\":1,\"possibleMove\":false},{\"x\":5,\"y\":2,\"possibleMove\":false},{\"x\":5,\"y\":3,\"possibleMove\":false},{\"x\":5,\"y\":4,\"possibleMove\":false},{\"x\":5,\"y\":5,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        move = new GameRule(fields);
        for (Field[] fieldArray : fields) {
            for (Field field : fieldArray) {
                assertEquals(field.isPossibleMove(), move.isMoveAllowed(field, Color.WHITE));
            }
        }

        // test 4
        content = "[[{\"x\":0,\"y\":0,\"possibleMove\":true},{\"x\":0,\"y\":1,\"possibleMove\":true},{\"x\":0,\"y\":2,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":3,\"possibleMove\":false},{\"x\":0,\"y\":4,\"possibleMove\":false},{\"x\":0,\"y\":5,\"possibleMove\":true}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":5,\"possibleMove\":false}],[{\"x\":2,\"y\":0,\"possibleMove\":false},{\"x\":2,\"y\":1,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"x\":2,\"y\":5,\"possibleMove\":true}],[{\"x\":3,\"y\":0,\"possibleMove\":false},{\"x\":3,\"y\":1,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":5,\"possibleMove\":false}],[{\"x\":4,\"y\":0,\"possibleMove\":false},{\"x\":4,\"y\":1,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":3,\"possibleMove\":false},{\"x\":4,\"y\":4,\"possibleMove\":true},{\"x\":4,\"y\":5,\"possibleMove\":true}],[{\"x\":5,\"y\":0,\"possibleMove\":false},{\"x\":5,\"y\":1,\"possibleMove\":false},{\"x\":5,\"y\":2,\"possibleMove\":true},{\"x\":5,\"y\":3,\"possibleMove\":false},{\"x\":5,\"y\":4,\"possibleMove\":false},{\"x\":5,\"y\":5,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        move = new GameRule(fields);
        for (Field[] fieldArray : fields) {
            for (Field field : fieldArray) {
                assertEquals(field.isPossibleMove(), move.isMoveAllowed(field, Color.BLACK));
            }
        }

        // test 5
        content = "[[{\"x\":0,\"y\":0,\"possibleMove\":false},{\"x\":0,\"y\":1,\"possibleMove\":false},{\"x\":0,\"y\":2,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":3,\"possibleMove\":false},{\"x\":0,\"y\":4,\"possibleMove\":false},{\"x\":0,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":5,\"possibleMove\":false}],[{\"x\":2,\"y\":0,\"possibleMove\":false},{\"x\":2,\"y\":1,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"x\":2,\"y\":5,\"possibleMove\":false}],[{\"x\":3,\"y\":0,\"possibleMove\":false},{\"x\":3,\"y\":1,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":5,\"possibleMove\":false}],[{\"x\":4,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":3,\"possibleMove\":false},{\"x\":4,\"y\":4,\"possibleMove\":false},{\"x\":4,\"y\":5,\"possibleMove\":false}],[{\"x\":5,\"y\":0,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":2,\"possibleMove\":false},{\"x\":5,\"y\":3,\"possibleMove\":true},{\"x\":5,\"y\":4,\"possibleMove\":false},{\"x\":5,\"y\":5,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        move = new GameRule(fields);
        for (Field[] fieldArray : fields) {
            for (Field field : fieldArray) {
                assertEquals(field.isPossibleMove(), move.isMoveAllowed(field, Color.WHITE));
            }
        }

        // test 6
        content = "[[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":0,\"possibleMove\":false},{\"x\":3,\"y\":1,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":5,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        move = new GameRule(fields);
        for (Field[] fieldArray : fields) {
            for (Field field : fieldArray) {
                assertEquals(field.isPossibleMove(), move.isMoveAllowed(field, Color.WHITE));
            }
        }

        // test 7
        content = "[[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":5,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        move = new GameRule(fields);
        for (Field[] fieldArray : fields) {
            for (Field field : fieldArray) {
                assertEquals(field.isPossibleMove(), move.isMoveAllowed(field, Color.BLACK));
            }
        }
    }

    @Test
    public void getPossibleMoves() throws Exception {
        String content;

        Field[][] fields;
        Gson gson = new GsonBuilder().create();

        // test 1
        content = "[[{\"x\":0,\"y\":0,\"possibleMove\":false},{\"x\":0,\"y\":1,\"possibleMove\":false},{\"x\":0,\"y\":2,\"possibleMove\":false},{\"x\":0,\"y\":3,\"possibleMove\":true},{\"x\":0,\"y\":4,\"possibleMove\":true},{\"x\":0,\"y\":5,\"possibleMove\":false},{\"x\":0,\"y\":6,\"possibleMove\":false},{\"x\":0,\"y\":7,\"possibleMove\":false}],[{\"x\":1,\"y\":0,\"possibleMove\":false},{\"x\":1,\"y\":1,\"possibleMove\":false},{\"x\":1,\"y\":2,\"possibleMove\":false},{\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"x\":1,\"y\":5,\"possibleMove\":true},{\"x\":1,\"y\":6,\"possibleMove\":false},{\"x\":1,\"y\":7,\"possibleMove\":false}],[{\"x\":2,\"y\":0,\"possibleMove\":false},{\"x\":2,\"y\":1,\"possibleMove\":false},{\"x\":2,\"y\":2,\"possibleMove\":false},{\"x\":2,\"y\":3,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":5,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":6,\"possibleMove\":false},{\"x\":2,\"y\":7,\"possibleMove\":false}],[{\"x\":3,\"y\":0,\"possibleMove\":false},{\"x\":3,\"y\":1,\"possibleMove\":false},{\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":4,\"possibleMove\":false},{\"x\":3,\"y\":5,\"possibleMove\":true},{\"x\":3,\"y\":6,\"possibleMove\":false},{\"x\":3,\"y\":7,\"possibleMove\":false}],[{\"x\":4,\"y\":0,\"possibleMove\":false},{\"x\":4,\"y\":1,\"possibleMove\":false},{\"x\":4,\"y\":2,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":4,\"possibleMove\":false},{\"x\":4,\"y\":5,\"possibleMove\":false},{\"x\":4,\"y\":6,\"possibleMove\":false},{\"x\":4,\"y\":7,\"possibleMove\":false}],[{\"x\":5,\"y\":0,\"possibleMove\":false},{\"x\":5,\"y\":1,\"possibleMove\":false},{\"x\":5,\"y\":2,\"possibleMove\":true},{\"x\":5,\"y\":3,\"possibleMove\":true},{\"x\":5,\"y\":4,\"possibleMove\":false},{\"x\":5,\"y\":5,\"possibleMove\":false},{\"x\":5,\"y\":6,\"possibleMove\":false},{\"x\":5,\"y\":7,\"possibleMove\":false}],[{\"x\":6,\"y\":0,\"possibleMove\":false},{\"x\":6,\"y\":1,\"possibleMove\":false},{\"x\":6,\"y\":2,\"possibleMove\":false},{\"x\":6,\"y\":3,\"possibleMove\":false},{\"x\":6,\"y\":4,\"possibleMove\":false},{\"x\":6,\"y\":5,\"possibleMove\":false},{\"x\":6,\"y\":6,\"possibleMove\":false},{\"x\":6,\"y\":7,\"possibleMove\":false}],[{\"x\":7,\"y\":0,\"possibleMove\":false},{\"x\":7,\"y\":1,\"possibleMove\":false},{\"x\":7,\"y\":2,\"possibleMove\":false},{\"x\":7,\"y\":3,\"possibleMove\":false},{\"x\":7,\"y\":4,\"possibleMove\":false},{\"x\":7,\"y\":5,\"possibleMove\":false},{\"x\":7,\"y\":6,\"possibleMove\":false},{\"x\":7,\"y\":7,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        GameRule move = new GameRule(fields);
        assertEquals(8, move.getPossibleMoves());

        // test 2
        content = "[[{\"x\":0,\"y\":0,\"possibleMove\":false},{\"x\":0,\"y\":1,\"possibleMove\":false},{\"x\":0,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":3,\"possibleMove\":false},{\"x\":0,\"y\":4,\"possibleMove\":false},{\"x\":0,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"x\":1,\"y\":5,\"possibleMove\":false}],[{\"x\":2,\"y\":0,\"possibleMove\":false},{\"x\":2,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"x\":2,\"y\":5,\"possibleMove\":false}],[{\"x\":3,\"y\":0,\"possibleMove\":false},{\"x\":3,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"x\":3,\"y\":4,\"possibleMove\":true},{\"x\":3,\"y\":5,\"possibleMove\":false}],[{\"x\":4,\"y\":0,\"possibleMove\":false},{\"x\":4,\"y\":1,\"possibleMove\":false},{\"x\":4,\"y\":2,\"possibleMove\":false},{\"x\":4,\"y\":3,\"possibleMove\":false},{\"x\":4,\"y\":4,\"possibleMove\":true},{\"x\":4,\"y\":5,\"possibleMove\":false}],[{\"x\":5,\"y\":0,\"possibleMove\":false},{\"x\":5,\"y\":1,\"possibleMove\":false},{\"x\":5,\"y\":2,\"possibleMove\":false},{\"x\":5,\"y\":3,\"possibleMove\":false},{\"x\":5,\"y\":4,\"possibleMove\":false},{\"x\":5,\"y\":5,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        move = new GameRule(fields);
        assertEquals(2, move.getPossibleMoves());

        // test 3
        content = "[[{\"x\":0,\"y\":0,\"possibleMove\":false},{\"x\":0,\"y\":1,\"possibleMove\":false},{\"x\":0,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":3,\"possibleMove\":false},{\"x\":0,\"y\":4,\"possibleMove\":false},{\"x\":0,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"x\":1,\"y\":5,\"possibleMove\":true}],[{\"x\":2,\"y\":0,\"possibleMove\":false},{\"x\":2,\"y\":1,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"x\":2,\"y\":5,\"possibleMove\":true}],[{\"x\":3,\"y\":0,\"possibleMove\":false},{\"x\":3,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":5,\"possibleMove\":false}],[{\"x\":4,\"y\":0,\"possibleMove\":false},{\"x\":4,\"y\":1,\"possibleMove\":false},{\"x\":4,\"y\":2,\"possibleMove\":false},{\"x\":4,\"y\":3,\"possibleMove\":false},{\"x\":4,\"y\":4,\"possibleMove\":false},{\"x\":4,\"y\":5,\"possibleMove\":false}],[{\"x\":5,\"y\":0,\"possibleMove\":false},{\"x\":5,\"y\":1,\"possibleMove\":false},{\"x\":5,\"y\":2,\"possibleMove\":false},{\"x\":5,\"y\":3,\"possibleMove\":false},{\"x\":5,\"y\":4,\"possibleMove\":false},{\"x\":5,\"y\":5,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        move = new GameRule(fields);
        assertEquals(3, move.getPossibleMoves());

        // test 4
        content = "[[{\"x\":0,\"y\":0,\"possibleMove\":true},{\"x\":0,\"y\":1,\"possibleMove\":true},{\"x\":0,\"y\":2,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":3,\"possibleMove\":false},{\"x\":0,\"y\":4,\"possibleMove\":false},{\"x\":0,\"y\":5,\"possibleMove\":true}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":5,\"possibleMove\":false}],[{\"x\":2,\"y\":0,\"possibleMove\":false},{\"x\":2,\"y\":1,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"x\":2,\"y\":5,\"possibleMove\":true}],[{\"x\":3,\"y\":0,\"possibleMove\":false},{\"x\":3,\"y\":1,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":5,\"possibleMove\":false}],[{\"x\":4,\"y\":0,\"possibleMove\":false},{\"x\":4,\"y\":1,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":3,\"possibleMove\":false},{\"x\":4,\"y\":4,\"possibleMove\":true},{\"x\":4,\"y\":5,\"possibleMove\":true}],[{\"x\":5,\"y\":0,\"possibleMove\":false},{\"x\":5,\"y\":1,\"possibleMove\":false},{\"x\":5,\"y\":2,\"possibleMove\":true},{\"x\":5,\"y\":3,\"possibleMove\":false},{\"x\":5,\"y\":4,\"possibleMove\":false},{\"x\":5,\"y\":5,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        move = new GameRule(fields);
        assertEquals(11, move.getPossibleMoves());

        // test 5
        content = "[[{\"x\":0,\"y\":0,\"possibleMove\":false},{\"x\":0,\"y\":1,\"possibleMove\":false},{\"x\":0,\"y\":2,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":3,\"possibleMove\":false},{\"x\":0,\"y\":4,\"possibleMove\":false},{\"x\":0,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":5,\"possibleMove\":false}],[{\"x\":2,\"y\":0,\"possibleMove\":false},{\"x\":2,\"y\":1,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"x\":2,\"y\":5,\"possibleMove\":false}],[{\"x\":3,\"y\":0,\"possibleMove\":false},{\"x\":3,\"y\":1,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":5,\"possibleMove\":false}],[{\"x\":4,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":3,\"possibleMove\":false},{\"x\":4,\"y\":4,\"possibleMove\":false},{\"x\":4,\"y\":5,\"possibleMove\":false}],[{\"x\":5,\"y\":0,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":2,\"possibleMove\":false},{\"x\":5,\"y\":3,\"possibleMove\":true},{\"x\":5,\"y\":4,\"possibleMove\":false},{\"x\":5,\"y\":5,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        move = new GameRule(fields);
        assertEquals(5, move.getPossibleMoves());

        // test 6
        content = "[[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":0,\"possibleMove\":false},{\"x\":3,\"y\":1,\"possibleMove\":true},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":5,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        move = new GameRule(fields);
        assertEquals(1, move.getPossibleMoves());

        // test 7
        content = "[[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":0,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":0,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":1,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":1,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":2,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":2,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":3,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":3,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":4,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":4,\"y\":5,\"possibleMove\":false}],[{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":0,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":1,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"WHITE\"},\"x\":5,\"y\":2,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":3,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":4,\"possibleMove\":false},{\"stone\":{\"stoneColor\":\"BLACK\"},\"x\":5,\"y\":5,\"possibleMove\":false}]]";
        fields = gson.fromJson(content, Field[][].class);

        move = new GameRule(fields);
        assertEquals(0, move.getPossibleMoves());
    }

}